services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: backend
    ports:
      - "5000:4000"
    env_file:
      - ./apps/server/.env
    restart: always

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env.local
    depends_on:
      - server
    restart: always