import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/lib/components/providers/session-provider";
import { ThemeProvider } from "@repo/context-providers"; // ← Add this import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>  {/* ← Wrap with ThemeProvider */}
          <div className="bg-[#F1F5F9] dark:bg-[#0F172A] min-h-screen">
            <SessionProvider>
              {children}
            </SessionProvider>
          </div>
        </ThemeProvider>  {/* ← Close ThemeProvider */}
      </body>
    </html>
  );
}